language: R
sudo: false
cache: packages
r: bioc-release
addons:
  apt:
    packages:
    - perl
warnings_are_errors: false
notifications:
  slack:
    on_success: never
    on_failure: never

dist: precise
sudo: required
