%\VignetteIndexEntry{R package for Intra-Sample Heterogeneity Scores}
%\VignetteKeywords{methylation, RnBeads}

\documentclass{article}

\title{ISH - R package for Intra-Sample Heterogeneity Scores}

\author{Michael Scherer}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

\section{Introduction}

This vignette desribes the functionalities included in the ISH R package. We describe the Intra-Sample Heterogeneity Scores FDRP, qFDRP, PDR, Epipolymorphism and Entropy. The package is able to compute each of those scores from bisulfite sequencing data.

\end{document}
